services:
  viaggia-frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.dev
    container_name: viaggia-frontend
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:7164/api
    ports:
      - "3000:3000"
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
    networks:
      - viaggia-network

networks:
  viaggia-network:
    external: true

volumes:
  node_modules:
